[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
viaIR = true
optimizer = true
optimizerRuns = 1000
fs_permissions = [
    { access = "read", path = "./config.json" }
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${process.env.SEPOLIA_API_KEY}"
sepolia = "https://rpc.ankr.com/eth_sepolia"
op_sepolia = "https://sepolia.optimism.io"
op_mainnet = "https://mainnet.optimism.io"
arbitrum = "https://arb1.arbitrum.io/rpc"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
