name: Foundry CI

on:
  push:
    branches:
      - HAMT-7-git-ci-cd-in-project
  pull_request:

jobs:
  foundry-ci:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          submodules: recursive

      # Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      # Set up environment variables
      - name: Set environment variables
        run: echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV

      # Run Foundry tests
      - name: Run Foundry Tests (Sepolia Fork)
        run: forge test -vvv --via-ir --optimizer-runs 1100 --fork-url https://sepolia.drpc.org
